import { ClerkProvider } from '@clerk/nextjs'
// import { ErrorWrapper } from './error-wrapper'
import '/globals.css'
import { Navigation } from './components/navigation'

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// default title metadata

export const metadata={
  title:{default :"Next.js",
  template:"%s | nextjs demo",    //adding sufixes and prefixes to title.this property applied to child route.if my blog title is blog then its display as "blog | nextjs demo"
  absolute:""},
  description:"Generated by Next.js"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en"> 
      <body>
        <div>New Feature</div>
      {/* <ErrorWrapper> */}
      <Navigation/>
        {children}
        {/* </ErrorWrapper> */}
      </body>
    </html>
    </ClerkProvider>
  )
}
